server:
  port: 777

spring:
  application:
    name: API-GATEWAY
  profiles:
    active:
      - default
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://authentication-service/
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authentication-service
                fallbackuri: forward:/authenticationFallback

        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallback

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:700/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

client:
  authentication-service:
    url: http://localhost:701/api/v1/auth/validation
